name = "clean-jl"

[sysimg]
filter_stdlibs=false
incremental=false

[sysimg.precompile]
execution_file = ["test/runtests.jl"]

[application]
filter_stdlibs=false
incremental=false

[application.precompile]
execution_file = ["test/runtests.jl"]
